var fullpage = new fullpage('#fullpage', {
    //Navigation
    menu: '.menu',
    lockAnchors: false,
    anchors: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19'],
    navigation: true,
    navigationPosition: 'right',
    navigationTooltips: ['about', 'projects', 'process'],
    showActiveTooltip: false,
    slidesNavigation: true,
    slidesNavPosition: 'bottom',
    //Scrolling
    css3: true,
    scrollingSpeed: 700,
    autoScrolling: true,
    fitToSection: true,
    fitToSectionDelay: 1000,
    scrollBar: false,
    easing: 'easeInOutCubic',
    easingcss3: 'ease',
    loopBottom: false,
    loopTop: false,
    loopHorizontal: true,
    continuousVertical: false,
    continuousHorizontal: false,
    scrollHorizontally: false,
    interlockedSlides: false,
    dragAndMove: false,
    offsetSections: false,
    resetSliders: false,
    fadingEffect: false,
    normalScrollElements: '',
    scrollOverflow: false,
    scrollOverflowReset: false,
    scrollOverflowOptions: null,
    touchSensitivity: 15,
    normalScrollElementTouchThreshold: 5,
    bigSectionsDestination: null,
    //Accessibility
    keyboardScrolling: true,
    animateAnchor: true,
    recordHistory: false,
    //Design
    controlArrows: true,
    verticalCentered: true,
    sectionsColor: ['', ''],
    paddingTop: '',
    paddingBottom: '',
    fixedElements: '',
    responsiveWidth: 0,
    responsiveHeight: 0,
    responsiveSlides: false,
    parallax: false,
    parallaxOptions: { type: 'reveal', percentage: 62, property: 'translate' },
    cards: false,
    cardsOptions: { perspective: 100, fadeContent: true, fadeBackground: true },
    //Custom selectors
    sectionSelector: '.section',
    slideSelector: '.slide',
    controlArrows: true,
    lazyLoading: false,
    //events
    onLeave: function (origin, destination, direction) { },
    afterLoad: function (origin, destination, direction) { },
    afterRender: function () { },
    afterResize: function () { width, height },
    afterResponsive: function (isResponsive) { },
    afterSlideLoad: function (section, origin, destination, direction) { },
    onSlideLeave: function (section, origin, destination, direction) { }
});